/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { MediaDto } from '../models';
import { RequestMediaDto } from '../models';
/**
 * S3Api - axios parameter creator
 * @export
 */
export const S3ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get media message
         * @summary Get Media
         * @param {string} apikey apikey from .env
         * @param {string} instance Name of instance
         * @param {RequestMediaDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMedia: async (apikey: string, instance: string, body?: RequestMediaDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apikey' is not null or undefined
            if (apikey === null || apikey === undefined) {
                throw new RequiredError('apikey','Required parameter apikey was null or undefined when calling getMedia.');
            }
            // verify required parameter 'instance' is not null or undefined
            if (instance === null || instance === undefined) {
                throw new RequiredError('instance','Required parameter instance was null or undefined when calling getMedia.');
            }
            const localVarPath = `/s3/getMedia/{instance}`
                .replace(`{${"instance"}}`, encodeURIComponent(String(instance)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (apikey !== undefined && apikey !== null) {
                localVarHeaderParameter['apikey'] = String(apikey);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get media message URL
         * @summary Get Media Url
         * @param {string} apikey apikey from .env
         * @param {string} instance Name of instance
         * @param {RequestMediaDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMediaUrl: async (apikey: string, instance: string, body?: RequestMediaDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apikey' is not null or undefined
            if (apikey === null || apikey === undefined) {
                throw new RequiredError('apikey','Required parameter apikey was null or undefined when calling getMediaUrl.');
            }
            // verify required parameter 'instance' is not null or undefined
            if (instance === null || instance === undefined) {
                throw new RequiredError('instance','Required parameter instance was null or undefined when calling getMediaUrl.');
            }
            const localVarPath = `/s3/getMediaUrl/{instance}`
                .replace(`{${"instance"}}`, encodeURIComponent(String(instance)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (apikey !== undefined && apikey !== null) {
                localVarHeaderParameter['apikey'] = String(apikey);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * S3Api - functional programming interface
 * @export
 */
export const S3ApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get media message
         * @summary Get Media
         * @param {string} apikey apikey from .env
         * @param {string} instance Name of instance
         * @param {RequestMediaDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMedia(apikey: string, instance: string, body?: RequestMediaDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<MediaDto>>>> {
            const localVarAxiosArgs = await S3ApiAxiosParamCreator(configuration).getMedia(apikey, instance, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get media message URL
         * @summary Get Media Url
         * @param {string} apikey apikey from .env
         * @param {string} instance Name of instance
         * @param {RequestMediaDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMediaUrl(apikey: string, instance: string, body?: RequestMediaDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MediaDto>>> {
            const localVarAxiosArgs = await S3ApiAxiosParamCreator(configuration).getMediaUrl(apikey, instance, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * S3Api - factory interface
 * @export
 */
export const S3ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get media message
         * @summary Get Media
         * @param {string} apikey apikey from .env
         * @param {string} instance Name of instance
         * @param {RequestMediaDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMedia(apikey: string, instance: string, body?: RequestMediaDto, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<MediaDto>>> {
            return S3ApiFp(configuration).getMedia(apikey, instance, body, options).then((request) => request(axios, basePath));
        },
        /**
         * Get media message URL
         * @summary Get Media Url
         * @param {string} apikey apikey from .env
         * @param {string} instance Name of instance
         * @param {RequestMediaDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMediaUrl(apikey: string, instance: string, body?: RequestMediaDto, options?: AxiosRequestConfig): Promise<AxiosResponse<MediaDto>> {
            return S3ApiFp(configuration).getMediaUrl(apikey, instance, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * S3Api - object-oriented interface
 * @export
 * @class S3Api
 * @extends {BaseAPI}
 */
export class S3Api extends BaseAPI {
    /**
     * Get media message
     * @summary Get Media
     * @param {string} apikey apikey from .env
     * @param {string} instance Name of instance
     * @param {RequestMediaDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof S3Api
     */
    public async getMedia(apikey: string, instance: string, body?: RequestMediaDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<MediaDto>>> {
        return S3ApiFp(this.configuration).getMedia(apikey, instance, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get media message URL
     * @summary Get Media Url
     * @param {string} apikey apikey from .env
     * @param {string} instance Name of instance
     * @param {RequestMediaDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof S3Api
     */
    public async getMediaUrl(apikey: string, instance: string, body?: RequestMediaDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<MediaDto>> {
        return S3ApiFp(this.configuration).getMediaUrl(apikey, instance, body, options).then((request) => request(this.axios, this.basePath));
    }
}
