/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { TemplateDto } from '../models';
/**
 * TemplateApi - axios parameter creator
 * @export
 */
export const TemplateApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get templates
         * @summary Your GET endpoint
         * @param {string} instance Name of instance
         * @param {string} [apikey] apikey from .env
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplates: async (instance: string, apikey?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instance' is not null or undefined
            if (instance === null || instance === undefined) {
                throw new RequiredError('instance','Required parameter instance was null or undefined when calling getTemplates.');
            }
            const localVarPath = `/template/find/{instance}`
                .replace(`{${"instance"}}`, encodeURIComponent(String(instance)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (apikey !== undefined && apikey !== null) {
                localVarHeaderParameter['apikey'] = String(apikey);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TemplateApi - functional programming interface
 * @export
 */
export const TemplateApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get templates
         * @summary Your GET endpoint
         * @param {string} instance Name of instance
         * @param {string} [apikey] apikey from .env
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTemplates(instance: string, apikey?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<TemplateDto>>>> {
            const localVarAxiosArgs = await TemplateApiAxiosParamCreator(configuration).getTemplates(instance, apikey, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TemplateApi - factory interface
 * @export
 */
export const TemplateApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get templates
         * @summary Your GET endpoint
         * @param {string} instance Name of instance
         * @param {string} [apikey] apikey from .env
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTemplates(instance: string, apikey?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<TemplateDto>>> {
            return TemplateApiFp(configuration).getTemplates(instance, apikey, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TemplateApi - object-oriented interface
 * @export
 * @class TemplateApi
 * @extends {BaseAPI}
 */
export class TemplateApi extends BaseAPI {
    /**
     * Get templates
     * @summary Your GET endpoint
     * @param {string} instance Name of instance
     * @param {string} [apikey] apikey from .env
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplateApi
     */
    public async getTemplates(instance: string, apikey?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<TemplateDto>>> {
        return TemplateApiFp(this.configuration).getTemplates(instance, apikey, options).then((request) => request(this.axios, this.basePath));
    }
}
