/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ButtonTemplateDto
 */
export interface ButtonTemplateDto {

    /**
     * @type {string}
     * @memberof ButtonTemplateDto
     */
    type: string;

    /**
     * @type {string}
     * @memberof ButtonTemplateDto
     */
    text: string;

    /**
     * @type {string}
     * @memberof ButtonTemplateDto
     */
    url?: string;
}
