/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ButtonTemplateDto } from './button-template-dto';
 /**
 * 
 *
 * @export
 * @interface ComponentDto
 */
export interface ComponentDto {

    /**
     * @type {string}
     * @memberof ComponentDto
     */
    type: string;

    /**
     * @type {string}
     * @memberof ComponentDto
     */
    text?: string;

    /**
     * @type {string}
     * @memberof ComponentDto
     */
    format?: string;

    /**
     * @type {boolean}
     * @memberof ComponentDto
     */
    add_security_recommendation?: boolean;

    /**
     * @type {number}
     * @memberof ComponentDto
     */
    code_expiration_minutes?: number;

    /**
     * @type {Array<ButtonTemplateDto>}
     * @memberof ComponentDto
     */
    buttons?: Array<ButtonTemplateDto>;
}
