/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DisappearingModeDto } from './disappearing-mode-dto';
 /**
 * 
 *
 * @export
 * @interface ContextInfoDto
 */
export interface ContextInfoDto {

    /**
     * @type {DisappearingModeDto}
     * @memberof ContextInfoDto
     */
    disappearingMode?: DisappearingModeDto;
}
