/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DocumentMessageDto
 */
export interface DocumentMessageDto {

    /**
     * @type {string}
     * @memberof DocumentMessageDto
     */
    url?: string;

    /**
     * @type {string}
     * @memberof DocumentMessageDto
     */
    fileName?: string;

    /**
     * @type {string}
     * @memberof DocumentMessageDto
     */
    mediaKey?: string;

    /**
     * @type {string}
     * @memberof DocumentMessageDto
     */
    mimetype?: string;

    /**
     * @type {number}
     * @memberof DocumentMessageDto
     */
    pageCount?: number;

    /**
     * @type {string}
     * @memberof DocumentMessageDto
     */
    directPath?: string;

    /**
     * @type {string}
     * @memberof DocumentMessageDto
     */
    fileLength?: string;

    /**
     * @type {string}
     * @memberof DocumentMessageDto
     */
    fileSha256?: string;

    /**
     * @type {string}
     * @memberof DocumentMessageDto
     */
    fileEncSha256?: string;

    /**
     * @type {string}
     * @memberof DocumentMessageDto
     */
    mediaKeyTimestamp?: string;
}
