/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { HydratedButtonDto } from './hydrated-button-dto';
import { ImageMessageDto } from './image-message-dto';
 /**
 * 
 *
 * @export
 * @interface HydratedTemplateDto
 */
export interface HydratedTemplateDto {

    /**
     * @type {string}
     * @memberof HydratedTemplateDto
     */
    hydratedContentText?: string | null;

    /**
     * @type {ImageMessageDto}
     * @memberof HydratedTemplateDto
     */
    imageMessage?: ImageMessageDto;

    /**
     * @type {Array<HydratedButtonDto>}
     * @memberof HydratedTemplateDto
     */
    hydratedButtons?: Array<HydratedButtonDto> | null;
}
