/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ImageMessageDto
 */
export interface ImageMessageDto {

    /**
     * @type {string}
     * @memberof ImageMessageDto
     */
    url?: string;

    /**
     * @type {number}
     * @memberof ImageMessageDto
     */
    width?: number;

    /**
     * @type {number}
     * @memberof ImageMessageDto
     */
    height?: number;

    /**
     * @type {string}
     * @memberof ImageMessageDto
     */
    caption?: string;

    /**
     * @type {string}
     * @memberof ImageMessageDto
     */
    mediaKey?: string;

    /**
     * @type {string}
     * @memberof ImageMessageDto
     */
    mimetype?: string;

    /**
     * @type {string}
     * @memberof ImageMessageDto
     */
    directPath?: string;

    /**
     * @type {string}
     * @memberof ImageMessageDto
     */
    fileLength?: string;

    /**
     * @type {string}
     * @memberof ImageMessageDto
     */
    fileSha256?: string;

    /**
     * @type {string}
     * @memberof ImageMessageDto
     */
    fileEncSha256?: string;

    /**
     * @type {string}
     * @memberof ImageMessageDto
     */
    thumbnailSha256?: string;

    /**
     * @type {string}
     * @memberof ImageMessageDto
     */
    mediaKeyTimestamp?: string;

    /**
     * @type {string}
     * @memberof ImageMessageDto
     */
    thumbnailEncSha256?: string;

    /**
     * @type {string}
     * @memberof ImageMessageDto
     */
    thumbnailDirectPath?: string;
}
