/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConversationMessageDto } from './conversation-message-dto';
import { KeyDto } from './key-dto';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2012
 */
export interface InlineResponse2012 {

    /**
     * @type {KeyDto}
     * @memberof InlineResponse2012
     */
    key?: KeyDto;

    /**
     * @type {ConversationMessageDto}
     * @memberof InlineResponse2012
     */
    message?: ConversationMessageDto;

    /**
     * @type {string}
     * @memberof InlineResponse2012
     */
    messageType?: string;

    /**
     * @type {number}
     * @memberof InlineResponse2012
     */
    messageTimestamp?: number;

    /**
     * @type {string}
     * @memberof InlineResponse2012
     */
    instanceId?: string;

    /**
     * @type {string}
     * @memberof InlineResponse2012
     */
    status?: string;

    /**
     * @type {string}
     * @memberof InlineResponse2012
     */
    source?: string;
}
