/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse2003Message } from './inline-response2003-message';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 {

    /**
     * @type {string}
     * @memberof InlineResponse2003
     */
    id: string;

    /**
     * @type {string}
     * @memberof InlineResponse2003
     */
    mediaUrl: string;

    /**
     * @type {string}
     * @memberof InlineResponse2003
     */
    createdAt: string;

    /**
     * @type {InlineResponse2003Message}
     * @memberof InlineResponse2003
     */
    message: InlineResponse2003Message;
}
