/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {

    /**
     * @type {boolean}
     * @memberof InlineResponse200
     */
    exists?: boolean;

    /**
     * @type {string}
     * @memberof InlineResponse200
     */
    jid?: string;

    /**
     * @type {string}
     * @memberof InlineResponse200
     */
    number?: string;
}
