/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse2001MessagesKey
 */
export interface InlineResponse2001MessagesKey {

    /**
     * @type {string}
     * @memberof InlineResponse2001MessagesKey
     */
    id?: string;

    /**
     * @type {boolean}
     * @memberof InlineResponse2001MessagesKey
     */
    fromMe?: boolean;

    /**
     * @type {string}
     * @memberof InlineResponse2001MessagesKey
     */
    remoteJid?: string;

    /**
     * @type {string}
     * @memberof InlineResponse2001MessagesKey
     */
    participant?: string;
}
