/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { KeyDto } from './key-dto';
import { MessageDto } from './message-dto';
 /**
 * 
 *
 * @export
 * @interface InlineResponse2013Message
 */
export interface InlineResponse2013Message {

    /**
     * @type {string}
     * @memberof InlineResponse2013Message
     */
    id: string;

    /**
     * @type {KeyDto}
     * @memberof InlineResponse2013Message
     */
    key: KeyDto;

    /**
     * @type {string}
     * @memberof InlineResponse2013Message
     */
    pushName: string;

    /**
     * @type {string}
     * @memberof InlineResponse2013Message
     */
    participant?: string | null;

    /**
     * @type {string}
     * @memberof InlineResponse2013Message
     */
    messageType: string;

    /**
     * @type {MessageDto}
     * @memberof InlineResponse2013Message
     */
    message: MessageDto;
}
