/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { KeyDto } from './key-dto';
import { MessageDto } from './message-dto';
 /**
 * 
 *
 * @export
 * @interface LastMessageDto
 */
export interface LastMessageDto {

    /**
     * @type {string}
     * @memberof LastMessageDto
     */
    id?: string;

    /**
     * @type {KeyDto}
     * @memberof LastMessageDto
     */
    key?: KeyDto;

    /**
     * @type {string}
     * @memberof LastMessageDto
     */
    pushName?: string;

    /**
     * @type {string}
     * @memberof LastMessageDto
     */
    participant?: string | null;

    /**
     * @type {string}
     * @memberof LastMessageDto
     */
    messageType?: string;

    /**
     * @type {MessageDto}
     * @memberof LastMessageDto
     */
    message?: MessageDto;

    /**
     * @type {string}
     * @memberof LastMessageDto
     */
    contextInfo?: string | null;

    /**
     * @type {string}
     * @memberof LastMessageDto
     */
    source?: string;

    /**
     * @type {number}
     * @memberof LastMessageDto
     */
    messageTimestamp?: number;

    /**
     * @type {string}
     * @memberof LastMessageDto
     */
    instanceId?: string;

    /**
     * @type {string}
     * @memberof LastMessageDto
     */
    sessionId?: string | null;

    /**
     * @type {string}
     * @memberof LastMessageDto
     */
    status?: string;
}
