/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MediaDtoMessage } from './media-dto-message';
 /**
 * 
 *
 * @export
 * @interface MediaDto
 */
export interface MediaDto {

    /**
     * @type {string}
     * @memberof MediaDto
     */
    id: string;

    /**
     * @type {string}
     * @memberof MediaDto
     */
    mediaUrl?: string;

    /**
     * @type {string}
     * @memberof MediaDto
     */
    createdAt: string;

    /**
     * @type {MediaDtoMessage}
     * @memberof MediaDto
     */
    message: MediaDtoMessage;
}
