/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ContextInfoDto } from './context-info-dto';
 /**
 * 
 *
 * @export
 * @interface VideoMessageDto
 */
export interface VideoMessageDto {

    /**
     * @type {string}
     * @memberof VideoMessageDto
     */
    url?: string;

    /**
     * @type {number}
     * @memberof VideoMessageDto
     */
    width?: number;

    /**
     * @type {number}
     * @memberof VideoMessageDto
     */
    height?: number;

    /**
     * @type {number}
     * @memberof VideoMessageDto
     */
    seconds?: number;

    /**
     * @type {string}
     * @memberof VideoMessageDto
     */
    mediaKey?: string;

    /**
     * @type {string}
     * @memberof VideoMessageDto
     */
    mimetype?: string;

    /**
     * @type {boolean}
     * @memberof VideoMessageDto
     */
    viewOnce?: boolean;

    /**
     * @type {string}
     * @memberof VideoMessageDto
     */
    directPath?: string;

    /**
     * @type {string}
     * @memberof VideoMessageDto
     */
    fileLength?: string;

    /**
     * @type {string}
     * @memberof VideoMessageDto
     */
    fileSha256?: string;

    /**
     * @type {ContextInfoDto}
     * @memberof VideoMessageDto
     */
    contextInfo?: ContextInfoDto;

    /**
     * @type {boolean}
     * @memberof VideoMessageDto
     */
    gifPlayback?: boolean;

    /**
     * @type {string}
     * @memberof VideoMessageDto
     */
    fileEncSha256?: string;

    /**
     * @type {string}
     * @memberof VideoMessageDto
     */
    jpegThumbnail?: string;

    /**
     * @type {string}
     * @memberof VideoMessageDto
     */
    gifAttribution?: string;

    /**
     * @type {string}
     * @memberof VideoMessageDto
     */
    mediaKeyTimestamp?: string;
}
