/* tslint:disable */
/* eslint-disable */
/**
 * whatsapp-api
 * Endpoints de whatsapp-api
 *
 * OpenAPI spec version: 1.0
 * Contact: libgot@libgot.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { WhereFindContactsDtoWhere } from './where-find-contacts-dto-where';
 /**
 * 
 *
 * @export
 * @interface WhereFindContactsDto
 */
export interface WhereFindContactsDto {

    /**
     * @type {WhereFindContactsDtoWhere}
     * @memberof WhereFindContactsDto
     */
    where?: WhereFindContactsDtoWhere;
}
